const fs = require('fs');
const path = require('path');

const MARKER = '<!-- markdash:generated -->';

function render(model) {
  const s = model.summary;
  const lines = [];
  lines.push(MARKER);
  lines.push('');
  lines.push('_This block is generated by `markdash sync`. Do not edit by hand._');
  lines.push('');
  lines.push(`- Documents: ${s.totals.documents} (tasks ${s.totals.tasks} / decisions ${s.totals.decisions} / risks ${s.totals.risks} / tests ${s.totals.tests})`);
  const ts = s.tasks.by_status;
  lines.push(`- Tasks by status: ${Object.entries(ts).map(([k, v]) => `${k} ${v}`).join(', ') || 'none'}`);
  if (s.tasks.blocked.length) lines.push(`- Blocked: ${s.tasks.blocked.map((t) => `[${t.title}](${t.path})`).join(', ')}`);
  if (s.tasks.overdue.length) lines.push(`- Overdue: ${s.tasks.overdue.map((t) => `[${t.title}](${t.path}) (due ${t.due})`).join(', ')}`);
  if (s.risks.high.length) lines.push(`- High risks: ${s.risks.high.map((t) => `[${t.title}](${t.path})`).join(', ')}`);
  if (s.stale.length) lines.push(`- Possibly stale: ${s.stale.map((t) => `[${t.title}](${t.path}) (${t.age_days}d since update)`).join(', ')}`);
  lines.push('');
  lines.push('**Recently updated**');
  for (const d of s.recent.slice(0, 5)) {
    lines.push(`- ${d.updated_at} [${d.title}](${d.path}) \`${d.type}/${d.status}\``);
  }
  lines.push('');
  return lines.join('\n');
}

function updateIndexFile(root, model) {
  const indexPath = path.join(root, model.config.docsDir, 'index.md');
  if (!fs.existsSync(indexPath)) return false;
  const prev = fs.readFileSync(indexPath, 'utf8');
  const block = render(model);
  const idx = prev.indexOf(MARKER);
  const next = idx === -1 ? prev.replace(/\s*$/, '\n\n') + block : prev.slice(0, idx) + block;
  if (next !== prev) fs.writeFileSync(indexPath, next);
  return true;
}

module.exports = { updateIndexFile, MARKER };
